### ISSUE TITLE
在RAX50路由器上，显示hbbs 进程未运行！一直重启

### ISSUE THREAD

**Issue by aron566** [everstu/Koolcenter_rustdesk#1]
日志如下：
[2023-09-01 13:08:02.354758 +08:00] INFO [src/common.rs:121] Private key comes from id_ed25519
[2023-09-01 13:08:02.354853 +08:00] INFO [src/peer.rs:84] DB_URL=/koolshare/configs/rustdesk/db_v2.sqlite3
Error: An error occured while creating a new object: error returned from database: disk I/O error

**Comment by everstu** [comment]
> 日志如下： [2023-09-01 13:08:02.354758 +08:00] INFO [src/common.rs:121] Private key comes from id_ed25519 [2023-09-01 13:08:02.354853 +08:00] INFO [src/peer.rs:84] DB_URL=/koolshare/configs/rustdesk/db_v2.sqlite3 Error: An error occured while creating a new object: error returned from database: disk I/O error

I/O error，jffs格式不支持db文件读写，建议插U盘，并安装usb2jffs解决。
