### ISSUE TITLE
HBBS服务无法启动

### ISSUE THREAD

**Issue by Tecorey** [everstu/Koolcenter_rustdesk#2]
路由器：Ac86U
版本：[386.2_2]
主程序版本：1.4.5
hbbs程序版本：1.1.11-1
hbbr程序版本：1.1.11-1
启用或者重启的时候的日志：
【2024年07月22日 13:22:29】: 🔁重启RustDesk Server！
【2024年07月22日 13:22:30】: 🟠启动 hbbs 进程，开启进程实时守护...
【2024年07月22日 13:22:34】: 🟢hbbs启动成功，pid：22300
【2024年07月22日 13:22:34】: 🟠启动 hbbr 进程，开启进程实时守护...
【2024年07月22日 13:22:40】: 🟢hbbr启动成功，pid：22395
【2024年07月22日 13:22:40】: 🧱添加IPV4防火墙入站规则...
【2024年07月22日 13:22:40】: 🧱打开 RustDesk IPV4服务端口：21115 21116 21117 21118 21119
【2024年07月22日 13:22:40】: 🧱添加IPV6防火墙入站规则...
【2024年07月22日 13:22:40】: 🧱打开 RustDesk IPV6服务端口：21115 21116 21117 21118 21119
【2024年07月22日 13:22:40】: ✅️插件已成功开启！
但是系统刷新后 hbbs系统就显示未运行
运行日志：
[2024-07-22 13:21:13.773932 +08:00] INFO [src/common.rs:122] Private key comes from id_ed25519
[2024-07-22 13:21:13.773969 +08:00] INFO [src/rendezvous_server.rs:1191] Key: 5qJUJOet1Cvpzm8NvA2rey8l2GTgJlfGFNnHp+dnC9A=
[2024-07-22 13:21:13.773987 +08:00] INFO [src/peer.rs:84] DB_URL=/koolshare/configs/rustdesk/db_v2.sqlite3
Error: An error occured while creating a new object: error returned from database: disk I/O error

**Comment by everstu** [comment]
> 路由器：Ac86U 版本：[386.2_2] 主程序版本：1.4.5 hbbs程序版本：1.1.11-1 hbbr程序版本：1.1.11-1 启用或者重启的时候的日志： 【2024年07月22日 13:22:29】: 🔁重启RustDesk Server！ 【2024年07月22日 13:22:30】: 🟠启动 hbbs 进程，开启进程实时守护... 【2024年07月22日 13:22:34】: 🟢hbbs启动成功，pid：22300 【2024年07月22日 13:22:34】: 🟠启动 hbbr 进程，开启进程实时守护... 【2024年07月22日 13:22:40】: 🟢hbbr启动成功，pid：22395 【2024年07月22日 13:22:40】: 🧱添加IPV4防火墙入站规则... 【2024年07月22日 13:22:40】: 🧱打开 RustDesk IPV4服务端口：21115 21116 21117 21118 21119 【2024年07月22日 13:22:40】: 🧱添加IPV6防火墙入站规则... 【2024年07月22日 13:22:40】: 🧱打开 RustDesk IPV6服务端口：21115 21116 21117 21118 21119 【2024年07月22日 13:22:40】: ✅️插件已成功开启！ 但是系统刷新后 hbbs系统就显示未运行 运行日志： [2024-07-22 13:21:13.773932 +08:00] INFO [src/common.rs:122] Private key comes from id_ed25519 [2024-07-22 13:21:13.773969 +08:00] INFO [src/rendezvous_server.rs:1191] Key: 5qJUJOet1Cvpzm8NvA2rey8l2GTgJlfGFNnHp+dnC9A= [2024-07-22 13:21:13.773987 +08:00] INFO [src/peer.rs:84] DB_URL=/koolshare/configs/rustdesk/db_v2.sqlite3 Error: An error occured while creating a new object: error returned from database: disk I/O error

```
[2024-07-22 13:21:13.773987 +08:00] INFO [src/peer.rs:84] DB_URL=/koolshare/configs/rustdesk/db_v2.sqlite3 Error: An error occured while creating a new object: error returned from database: disk I/O error
```
报错提示数据库读写I/O错误，请尝试安装并启用**usb2jffs**插件解决这个问题，因为部分路由器自带的jffs分区不允许db文件读写，这个是无法解决的。
