### ISSUE TITLE
大佬，求一个支持网件 R7000，固件号为 380.70_0-X7.9.1 的版本！

### ISSUE THREAD

**Issue by 921j** [everstu/Koolcenter_rustdesk#4]
如题，这几天快折腾疯了，想在刷了 380.70_0-X7.9.1 的 R7000 上部署 RustDesk，因为人常在外地，家里的老人不会电脑，手机除了网购刷头条抖音其他啥都不懂，经常搞出些莫名其妙的小问题来，故障说也说不清，于是考虑在路由器上部署 RustDesk，随时远程看能否方便些。
我先下了您的最新版本，用改 install.sh 的方法强制安装了上去，但发现无法正常运行，显示非法指令，又尝试在 entware 里装，却发现  armv7sf-k2.6 官方终止了更新，好在找到了个无私更新的大佬的地址 [https://maurerr.github.io/entware-armv7-k26](url) ，装上了 rustdesk-server_1.1.11-1-1_armv7-2.6，但是发现 hbbs 会报错，什么无效协议，hbbr 倒是运行正常，我用的 DDNS 是默认的 asuscomm，可以正常 ping 通，应该是可用的，hbbr 运行后扫 21117 端口也可以开启，就是 hbbs 不行，想自己编译一个最新版又不知从何而起。
除了这个外，380.70 一直用得好好的，难道要作死上386？
希望大佬有空闲的时候不吝出手相救！跪谢了！

**Comment by everstu** [comment]
我帮不了你哦，这个可能是你的机器固件不支持某个库导致的。
