### ISSUE TITLE
能否把api的服务一起加入

### ISSUE THREAD

**Issue by jiangjin19856** [everstu/Koolcenter_rustdesk#5]
首先感谢大佬开发的这款插件，让我只用路由就能使用自己的服务器，这样我能很方便管理自己的一些设备，但是有个问题如果我在别的电脑上面使用软件，又记不住设备的ID，这时就很需要登陆账号来同步我的设备ID，不知道能否增加api服务，实现账号注册与登陆，这样就能把所有的id同步到账号里面，到哪里用只要登陆账号就行了。不知我请求能否实现，再次感谢！！

**Comment by everstu** [comment]
这个不属于路由器插件功能了，这个属于密码本功能了，建议搜索密码本工具。
